# Generated by Django 5.2.4 on 2025-07-24 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='email',
        ),
    ]
