# Generated by Django 5.2.4 on 2025-07-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_remove_supplier_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='phone',
            new_name='contact',
        ),
    ]
